dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install -r requirements.txt
  - pip install codecov
  - python setup.py build_ext --inplace
script:
  - coverage run --source flowkit --omit="flowkit/tests/*" run_tests.py

after_success:
  - codecov
